import type { StudyGuideConfig } from "@tbe/types";

export const DSA_STUDY_GUIDE_CONFIGS: Record<string, StudyGuideConfig> = {
  ARRAY: {
    topic: "Arrays",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-arrays-work", label: "How Arrays work" },
      { divider: "Patterns" },
      { id: "sliding-window", label: "Sliding window" },
      { id: "hash-map", label: "Hash map" },
      { id: "prefix-sum", label: "Prefix sum" },
      { id: "kadanes", label: "Kadane's algorithm" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  STRING: {
    topic: "Strings",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-strings-work", label: "How Strings work" },
      { divider: "Patterns" },
      { id: "two-pointers", label: "Two pointers" },
      { id: "sliding-window", label: "Sliding window" },
      { id: "hash-map", label: "Hash map" },
      { id: "palindrome-expansion", label: "Palindrome expansion" },
      { id: "stack", label: "Stack" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  HASHMAP: {
    topic: "Hashmap",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-hash-maps-work", label: "How Hash Maps work" },
      { divider: "Patterns" },
      { id: "frequency-count", label: "Frequency count" },
      { id: "complement-lookup", label: "Complement lookup" },
      { id: "grouping", label: "Grouping" },
      { id: "sliding-window-hash-map", label: "Sliding window + hash map" },
      { id: "prefix-sum-hash-map", label: "Prefix sum + hash map" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  BINARY_SEARCH: {
    topic: "Binary Search",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-binary-search-works", label: "How Binary Search works" },
      { divider: "Patterns" },
      { id: "classic-exact-search", label: "Classic exact search" },
      { id: "lower-bound", label: "Lower bound" },
      { id: "parametric-binary-search", label: "Binary search on answer" },
      { id: "rotated-array-search", label: "Rotated array search" },
      { id: "2d-matrix-search", label: "Binary search on 2D matrix" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  LINKED_LIST: {
    topic: "Linked List",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-linked-lists-work", label: "How Linked Lists work" },
      { divider: "Patterns" },
      { id: "fast-slow-pointers", label: "Fast and slow pointers" },
      { id: "reversal", label: "Reversal" },
      { id: "merge-and-sort", label: "Merge and sort" },
      { id: "dummy-head-rewiring", label: "Dummy head and rewiring" },
      { id: "two-pointer-intersection", label: "Two pointers on lists" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  STACK: {
  topic: "Stack",
  hasStudyGuide: true,
  sections: [
    { id: "before-you-start", label: "Before you start" },
    { id: "how-stacks-work", label: "How Stacks work" },
    { divider: "Patterns" },
    { id: "matching-brackets", label: "Matching brackets" },
    { id: "monotonic-stack", label: "Monotonic stack" },
    { id: "stack-with-evaluation", label: "Expression evaluation" },
    { id: "stack-design", label: "Stack design" },
    { divider: null },
    { id: "cheat-sheet", label: "Cheat sheet" },
  ],
},
  SORTING: {
    topic: "Sorting",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-sorting-works", label: "How sorting works" },
      { divider: "Patterns" },
      { id: "bubble-sort", label: "Bubble sort" },
      { id: "selection-sort", label: "Selection sort" },
      { id: "insertion-sort", label: "Insertion sort" },
      { id: "shell-sort", label: "Shell sort" },
      { divider: "Advanced" },
      { id: "merge-sort", label: "Merge sort" },
      { id: "quicksort", label: "Quicksort" },
      { divider: "Non-comparison" },
      { id: "counting-and-radix-sort", label: "Counting & Radix sort" },
      { divider: "Applications" },
      { id: "sorting-as-first-step", label: "Sorting as a first step" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  QUEUE: {
    topic: "Queue",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-queues-work", label: "How Queues work" },
      { divider: "Patterns" },
      { id: "bfs-level-order", label: "BFS and level-order traversal" },
      { id: "monotonic-deque", label: "Monotonic deque" },
      { id: "priority-queue", label: "Priority queue (heap)" },
      { id: "queue-simulation", label: "Queue simulation" },
      { id: "topological-sort-bfs", label: "Topological sort (Kahn's BFS)" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  GRAPH: {
    topic: "Graph",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-graphs-work", label: "How Graphs work" },
      { divider: "Patterns" },
      { id: "bfs", label: "BFS" },
      { id: "dfs", label: "DFS" },
      { id: "union-find", label: "Union-Find" },
      { id: "topological-sort", label: "Topological sort" },
      { id: "dijkstra", label: "Dijkstra's algorithm" },
      { id: "cycle-detection", label: "Cycle detection" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  SLIDING_WINDOW: {
    topic: "Sliding Window",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-sliding-window-works", label: "How sliding window works" },
      { divider: "Patterns" },
      { id: "fixed-size-window", label: "Fixed-size window" },
      { id: "variable-size-window", label: "Variable-size window" },
      { id: "frequency-map-window", label: "Frequency map window" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  TWO_POINTERS: {
    topic: "Two Pointers",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-two-pointers-work", label: "How two pointers work" },
      { divider: null },
      { id: "inward-two-pointers", label: "Inward two pointers" },
      { id: "slow-fast-pointers", label: "Slow-fast pointers" },
      { id: "three-pointers", label: "Three pointers" },
      { id: "two-arrays-pointers", label: "Two pointers on two arrays" },
      { id: "fast-slow-cycle", label: "Fast-slow (cycle detection)" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  HEAP: {
    topic: "Heap",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-heaps-work", label: "How Heaps work" },
      { divider: null },
      { id: "top-k-elements", label: "Top K elements" },
      { id: "k-way-merge", label: "K-way merge" },
      { id: "two-heaps", label: "Two heaps" },
      { id: "greedy-heap", label: "Greedy with heap" },
      { id: "heap-with-lazy-deletion", label: "Heap with lazy deletion" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  TREE: {
    topic: "Tree",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-trees-work", label: "How trees work" },
      { divider: null },
      { id: "dfs-traversals", label: "DFS traversals" },
      { id: "bfs-level-order", label: "BFS / Level-order" },
      { id: "subtree-problems", label: "Subtree problems" },
      { id: "bst-properties", label: "BST properties" },
      { id: "path-problems", label: "Path problems" },
      { id: "tree-construction", label: "Tree construction" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  RECURSION: {
    topic: "Recursion",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-recursion-works", label: "How recursion works" },
      { divider: "Patterns" },
      { id: "linear-recursion", label: "Linear recursion" },
      { id: "divide-and-conquer", label: "Divide and conquer" },
      { id: "tree-recursion", label: "Tree recursion" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },

  GREEDY: {
    topic: "Greedy Algorithms",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-greedy-works", label: "How greedy works" },
      { divider: "Patterns" },
      { id: "interval-scheduling", label: "Interval Scheduling" },
      { id: "greedy-on-sorted-input", label: "Greedy on sorted input" },
      { id: "greedy-with-heap", label: "Greedy with heap" },
      { id: "jump-game-greedy", label: "Greedy sweep / jump game" },
      { id: "greedy-strings", label: "Greedy on strings" },
      { id: "greedy-graph", label: "Greedy on graphs" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  DFS: {
    topic: "Depth-First Search",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-dfs-works", label: "How DFS works" },
      { divider: "Patterns" },
      { id: "tree-dfs", label: "Tree DFS" },
      { id: "graph-dfs", label: "Graph DFS" },
      { id: "grid-dfs", label: "Grid DFS" },
      { id: "backtracking", label: "Backtracking" },
      { id: "topological-sort", label: "Topological Sort" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  BACKTRACKING: {
    topic: "Backtracking",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-backtracking-works", label: "How backtracking works" },
      { divider: "Patterns" },
      { id: "subsets", label: "Subsets" },
      { id: "permutations", label: "Permutations" },
      { id: "combinations", label: "Combinations" },
      { id: "path-search", label: "Path search" },
      { id: "constraint-satisfaction", label: "Constraint satisfaction" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  BFS: {
    topic: "Breadth-First Search",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-bfs-works", label: "How BFS works" },
      { divider: "Patterns" },
      { id: "standard-bfs", label: "Standard BFS" },
      { id: "multi-source-bfs", label: "Multi-source BFS" },
      { id: "level-order-bfs", label: "Level-order BFS" },
      { id: "word-ladder-bfs", label: "Word Ladder / State-space BFS" },
      { id: "bidirectional-bfs", label: "Bidirectional BFS" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },

  TRIE: {
    topic: "Trie",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-trie-works", label: "How a Trie works" },
      { divider: "Patterns" },
      { id: "basic-trie", label: "Basic Trie" },
      { id: "trie-with-wildcards", label: "Trie with wildcards" },
      { id: "trie-with-dfs-backtracking", label: "Trie + DFS / Backtracking" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  MONOTONIC_STACK: {
    topic: "Monotonic Stack",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-monotonic-stack-works", label: "How it works" },
      { divider: "Patterns" },
      { id: "next-greater-element", label: "Next Greater Element" },
      { id: "previous-smaller-element", label: "Previous Smaller Element" },
      { id: "largest-rectangle", label: "Largest Rectangle" },
      { id: "sliding-window-maximum", label: "Sliding Window Maximum" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
  DYNAMIC_PROGRAMMING: {
    topic: "Dynamic Programming",
    hasStudyGuide: true,
    sections: [
      { id: "before-you-start", label: "Before you start" },
      { id: "how-dp-works", label: "How DP works" },
      { divider: "Patterns" },
      { id: "linear-dp", label: "Linear DP" },
      { id: "knapsack", label: "0/1 Knapsack" },
      { id: "unbounded-knapsack", label: "Unbounded Knapsack" },
      { id: "two-sequence-dp", label: "Two-sequence DP" },
      { id: "interval-dp", label: "Interval DP" },
      { id: "dp-on-sequences", label: "DP on sequences (LIS)" },
      { divider: null },
      { id: "cheat-sheet", label: "Cheat sheet" },
    ],
  },
};
