import type { LucideIcon } from "lucide-react";
import {
  ArrowLeftRight,
  Binary,
  Boxes,
  Cpu,
  FileCode2,
  GitBranch,
  GitMerge,
  Globe2,
  Hash,
  Layers,
  LayoutGrid,
  Link2,
  ListTree,
  Network,
  Puzzle,
  Route,
  Rows3,
  Search,
  Shapes,
  Sigma,
  Sparkles,
  SquareStack,
  Workflow,
} from "lucide-react";

import type { DSATopicCanonicalSlug, DSATopicExtraSlug } from "./dsaTopics";

/** Lucide icons for DSA roadmap / topic pickers — keyed by topic slug. */
export const DSA_TOPIC_ROADMAP_ICON_MAP: Record<
  DSATopicCanonicalSlug | DSATopicExtraSlug,
  LucideIcon
> = {
  ARRAY: LayoutGrid,
  STRING: FileCode2,
  HASHMAP: Hash,
  SLIDING_WINDOW: Layers,
  PREFIX_SUM: Rows3,
  SORTING: ListTree,
  BINARY_SEARCH: Search,
  MATH: Sigma,
  BIT_MANIPULATION: Binary,
  RECURSION: Workflow,
  LINKED_LIST: Link2,
  STACK: SquareStack,
  QUEUE: Rows3,
  BINARY_TREE: GitMerge,
  TREE: Network,
  BST: ListTree,
  HEAP: Boxes,
  TRIE: Shapes,
  GRAPH: Globe2,
  BACKTRACKING: Route,
  DYNAMIC_PROGRAMMING: Puzzle,
  GREEDY: Sparkles,
  UNION_FIND: GitBranch,
  SIMULATION: Cpu,
  DESIGN: LayoutGrid,
  MONOTONIC_STACK: SquareStack,
  TWO_POINTERS: ArrowLeftRight,
  DFS: Network,
  BFS: Network,
};
