export {
  courseCompletionTemplate,
  courseEnrollmentTemplate,
  emailClient,
  emailTriggerService,
  interviewPrepEnrollmentTemplate,
  onboardingEmailTemplate,
  projectEnrollmentTemplate,
  sendCourseCompletionEmail,
  sendCourseEnrollmentEmail,
  sendEmail,
  sendInterviewPrepEnrollmentEmail,
  sendOnboardingEmail,
  sendProjectEnrollmentEmail,
  sendWelcomeEmail,
  welcomeEmailTemplate,
} from "@tbe/email";
